---
name: ci
on:
  push:
    branches: main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          tags: latest